import StaticPageTemplate from '@/components/templates/StaticPageTemplate'

export default function TermsPage() {
  return (
    <StaticPageTemplate 
      title="Terms of Service" 
      description="Please read these terms and conditions carefully before using our service."
      lastUpdated="January 1, 2025"
    >
      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing and using SpaceGrow.ai ("Service"), you accept and agree to be bound by the terms and provision of this agreement.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        SpaceGrow.ai provides IoT device management and sensor data visualization services for smart growing applications. Our service includes:
      </p>
      <ul>
        <li>Real-time sensor data monitoring</li>
        <li>Device management and control</li>
        <li>Data analytics and insights</li>
        <li>API access for device integration</li>
      </ul>

      <h2>3. User Accounts</h2>
      <p>
        To access certain features of our service, you must create an account. You are responsible for:
      </p>
      <ul>
        <li>Maintaining the confidentiality of your account credentials</li>
        <li>All activities that occur under your account</li>
        <li>Notifying us immediately of any unauthorized use</li>
      </ul>

      <h2>4. Device Usage and Data</h2>
      <p>
        You retain ownership of all data generated by your IoT devices. We collect and process this data to provide our services, including:
      </p>
      <ul>
        <li>Storing sensor readings and device status</li>
        <li>Providing analytics and insights</li>
        <li>Enabling device control and automation</li>
      </ul>

      <h2>5. Subscription and Billing</h2>
      <p>
        Our service operates on a subscription basis. By subscribing, you agree to:
      </p>
      <ul>
        <li>Pay all applicable fees for your chosen plan</li>
        <li>Automatic renewal unless cancelled</li>
        <li>Device limits based on your subscription tier</li>
      </ul>

      <h2>6. Prohibited Uses</h2>
      <p>You may not use our service:</p>
      <ul>
        <li>For any unlawful purpose or to solicit others to unlawful acts</li>
        <li>To violate any international, federal, provincial, or state regulations or laws</li>
        <li>To transmit malicious code, viruses, or any harmful content</li>
        <li>To interfere with or disrupt the service or servers</li>
      </ul>

      <h2>7. Service Availability</h2>
      <p>
        We strive to maintain 99.9% uptime but cannot guarantee uninterrupted service. Scheduled maintenance will be announced in advance when possible.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        SpaceGrow.ai shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.
      </p>

      <h2>9. Privacy Policy</h2>
      <p>
        Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the service.
      </p>

      <h2>10. Changes to Terms</h2>
      <p>
        We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting to our website.
      </p>

      <h2>11. Contact Information</h2>
      <p>
        If you have any questions about these Terms of Service, please contact us at legal@spacegrow.ai.
      </p>
    </StaticPageTemplate>
  )
}