# config/cable.yml - FINAL VERSION
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: SpaceGrow_production
  # ✅ PRODUCTION: Redis connection pool settings
  pool: <%= ENV.fetch("ACTIONCABLE_REDIS_POOL_SIZE", 5).to_i %>
  timeout: <%= ENV.fetch("ACTIONCABLE_REDIS_TIMEOUT", 5).to_i %>
  reconnect_attempts: <%= ENV.fetch("ACTIONCABLE_REDIS_RECONNECT_ATTEMPTS", 3).to_i %>