# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spacegrow_development
  username: <%= Rails.application.credentials.dig(:development, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: spacegrow_test
  username: <%= Rails.application.credentials.dig(:development, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
  host: localhost
  port: 5432

production:
  <<: *default
  # In production, use DATABASE_URL environment variable
  url: <%= ENV['DATABASE_URL'] %>
  # Fallback to credentials if DATABASE_URL not set
  database: <%= ENV['DATABASE_NAME'] || 'spacegrow_production' %>
  username: <%= ENV['DATABASE_USERNAME'] || Rails.application.credentials.dig(:production, :database, :username) %>
  password: <%= ENV['DATABASE_PASSWORD'] || Rails.application.credentials.dig(:production, :database, :password) %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>