# config/storage.yml

# Local storage for development (fallback)
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Test storage
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# MinIO configuration (S3-compatible)
# 🔒 Credentials come from Rails encrypted credentials, not ENV vars
minio:
  service: S3
  endpoint: <%= ENV['MINIO_ENDPOINT'] %>
  access_key_id: <%= Rails.application.credentials.dig(Rails.env.to_sym, :minio, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(Rails.env.to_sym, :minio, :secret_access_key) %>
  region: <%= ENV['MINIO_REGION'] || 'us-east-1' %>
  bucket: <%= ENV['MINIO_BUCKET'] %>
  force_path_style: true